
#include <fstream>

void amicable_numbers();
void circular_primes();
void coin_sums();
void counting_sundays();
void digit_cancelling_fractions();
void digit_fifth_powers();
void digit_factorials();
void distinct_powers();
void double_base_palindromes();
void even_fibonacci_numbers(int limit);
void factorial_digit_sum();
void highly_divisible_triangular_number();
void ith_prime(int);
void integer_right_triangles();
void large_fibonacci();
void large_sum(std::ifstream &infile);
void largest_palindrome_product(int limit);
void largest_prime_factor(int limit);
void largest_product_in_a_grid(int n, std::ifstream &infile);
void largest_product_in_a_series(int subsequence_length, std::ifstream &infile);
void lattice_paths();
void lexicographic_permutations();
void longest_collatz_sequence();
void maximum_path_sum(std::ifstream &triangle_file);
void multiples_of_three_or_five(int limit);
void name_scores(std::ifstream &infile);
void non_abundant_sums();
void number_spiral_diagonals();
void number_letter_counts();
void pandigital_products();
void power_digit_sum();
void quadratic_primes();
void reciprocal_cycles();
void smallest_multiple(int n);
void special_pythagorean_triplet();
void sum_square_difference(int n);
void summation_of_primes(int n);
void truncatable_primes();
